#pragma once
#include "animation_clip.hpp"// ActionTrack, SkeletonClip (imported animations)
#include "graphics.hpp"      // Image, Material, Mesh
#include "hidden.hpp"
#include "skeleton.hpp"
#include <entt/entt.hpp>
#include <fmt/core.h>
#include <functional>
#include <glm/gtc/quaternion.hpp>
#include <glm/vec3.hpp>
#include <memory>
#include <nlohmann/json.hpp>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>
#ifdef VAPOR_HAS_BOOST_PFR
#include <boost/pfr.hpp>
#endif

namespace Vapor {

class RenderScene;

// ============================================================================
// Scene blueprints — the declarative authoring layer.
//
// A SceneBlueprint is the parse/import artifact every authored source decodes
// into before anything becomes live: a scene JSON parses into one, and a model
// file (glTF/USD) imports into one (its node hierarchy = entities, its
// meshes/materials/images = the payload). instantiate() turns a blueprint into
// entt entities; the blueprint is a TEMPLATE (parse once, instantiate many,
// then discard) — the live scene is always the registry, never the blueprint.
//
// scene JSON schema (see parseSceneBlueprint):
//   {
//     "name": "chapter1",
//     "entities": [
//       { "name": "Sun", "light": { "type": "directional", "intensity": 2 } },
//       { "name": "Helmet", "source": "models/helmet.glb",   // model ref
//         "position": [0, 1, 0], "children": [ ... ] },
//       { "name": "Door", "prefab": "prefabs/door.json" }    // nested blueprint
//     ]
//   }
//
// The flow:
//   loadSceneBlueprint("scenes/main.json")   // parse + expand source/prefab refs
//   instantiate(registry, scene, blueprint)  // blueprint -> entities; stages each
//                                            //   mesh into the RenderScene world
//                                            //   pool once (shared geometry ->
//                                            //   repeated instantiation draws as
//                                            //   GPU instances)
//   Renderer::collectDrawables(registry,...) // entities -> per-instance MDI, each
//                                            //   frame
// ============================================================================

// A punctual light authored on an entity. Mirrors KHR_lights_punctual / the
// UsdLux subset; instantiate() resolves it into the engine light components
// (position/orientation come from the entity's TransformComponent).
struct LightBlueprint {
    enum class Type { Point, Directional, Spot };

    Type type = Type::Point;
    glm::vec3 color{ 1.0f };
    float intensity = 1.0f;
    float range = 0.0f;                            // 0 = unbounded (importer default)
    float innerConeAngle = 0.0f;                   // Spot only, radians
    float outerConeAngle = glm::radians(45.0f);    // Spot only, radians
};

// One entity of the authored hierarchy, stored FLAT: `parent` is an index into
// the owning SceneBlueprint::entities (-1 = top level), and parents always
// precede their children in the array. This carries the same hierarchy a
// nested tree would, but maps 1:1 onto entt entities + TransformComponent::
// parent instead of reintroducing a scene-graph object — the ECS owns the
// scene. The transform is LOCAL; mesh/light entries index the blueprint's flat
// payload vectors, so a mesh shared by several entities is stored once.
// Procedural primitive, generated by MeshBuilder at instantiate() time. The
// blueprint stays pure authoring data — no baked vertex payload — so the cook
// remains small and the geometry is rebuilt (cheaply) per load.
struct PrimitiveBlueprint {
    enum class Shape : uint8_t { None, Cube, Capsule, Cone, Triforce };
    Shape shape = Shape::None;
    float size = 1.0f;  // cube edge length / cone base size / capsule radius
    float height = 1.0f;// capsule only
    int material = -1;  // index into SceneBlueprint::materials, -1 = default
};

// One node-transform animation clip authored on an entity (glTF animations[]
// channels targeting a non-joint node; USD xform time samples). instantiate()
// registers each as an ActionTimeline in the AnimationClipLibrary and gives
// the entity a TimelinePlaybackComponent.
struct NodeClipBlueprint {
    std::string name;
    std::vector<ActionTrack> tracks;
};

struct EntityBlueprint {
    std::string name;
    glm::vec3 position{ 0.0f };
    glm::quat rotation{ 1.0f, 0.0f, 0.0f, 0.0f };
    glm::vec3 scale{ 1.0f };
    int parent = -1;        // index into SceneBlueprint::entities, -1 = top level
    std::vector<int> meshes;// indices into SceneBlueprint::meshes
    std::vector<int> lights;// indices into SceneBlueprint::lights
    std::vector<NodeClipBlueprint> clips;// per-node animation clips (glTF/USD)
    PrimitiveBlueprint primitive;

    // Authoring references, expanded by loadSceneBlueprint (kept afterwards as
    // provenance): a model file whose hierarchy is spliced under this entity,
    // or a nested scene JSON instantiated under it.
    std::string source;
    std::string prefab;

    // The entity's "components" JSON object, stored verbatim
    // ('{"pointLight": {...}, "sky": {...}}'); instantiate() resolves each key
    // through BlueprintComponents and emplaces the parsed component. Empty =
    // none. Kept as text so the blueprint (and its cook) stay independent of
    // which component types the running binary knows about.
    std::string componentsJson;
};

// A skeletal animation clip plus the skeleton it drives (index into
// SceneBlueprint::skeletons). Registered into the AnimationClipLibrary at
// instantiate() time; the skinning render path that will consume them is
// future work — importing preserves the data either way.
struct SkeletonClipBlueprint {
    int skeleton = -1;
    SkeletonClip clip;
};

struct SceneBlueprint {
    std::string name;
    std::vector<EntityBlueprint> entities;// flat, parent-indexed; parents precede children

    // Payload decoded by the model importers, referenced by index from entities.
    std::vector<std::shared_ptr<Mesh>> meshes;
    std::vector<std::shared_ptr<Material>> materials;
    std::vector<std::shared_ptr<Image>> images;
    std::vector<LightBlueprint> lights;
    std::vector<Skeleton> skeletons;             // glTF skins / UsdSkel hierarchies
    std::vector<SkeletonClipBlueprint> skeletonClips;// skeletal animations

    // Every file this blueprint was expanded from (the scene JSON itself is not
    // listed; source models and nested prefab JSONs are). Input set for the
    // cook-freshness hash.
    std::vector<std::string> sources;

    bool ok = false;
};

// ── Component appliers ──────────────────────────────────────────────────────
// Registry mapping a JSON key ("pointLight", "sky", ...) to a function that
// emplaces the matching component on an entity from a JSON object. The engine
// registers its own data-only components (see scene_blueprint.cpp); the app
// registers its gameplay components the same way — instantiate() never needs
// to know the type list. Aggregate components register via the Boost.PFR
// auto-applier (fields filled by name, same reflection the inspector draws
// with); components needing runtime setup (physics bodies, UI pages) take a
// hand-written applier via registerApplier.

namespace detail {
    // Name→entity map for the instantiate() batch currently applying its
    // components (null outside that window). Lets entt::entity fields be
    // authored as entity-name strings in scene JSON ("target": "Cube 1").
    const std::unordered_map<std::string, entt::entity>* entityNameScope();

    // RAII: installs the scope for the duration of a component-apply pass.
    struct EntityNameScopeGuard {
        explicit EntityNameScopeGuard(const std::unordered_map<std::string, entt::entity>* scope);
        ~EntityNameScopeGuard();
        EntityNameScopeGuard(const EntityNameScopeGuard&) = delete;
        EntityNameScopeGuard& operator=(const EntityNameScopeGuard&) = delete;
    };

#ifdef VAPOR_HAS_BOOST_PFR
    template<typename T> void fillFromJson(T& out, const nlohmann::json& j);

    // One named field: present in the JSON object -> parsed into `out`; absent
    // or unsupported (matrices, containers, handles) -> keep the default.
    template<typename V> void readField(std::string_view name, V& out, const nlohmann::json& obj) {
        const auto it = obj.find(std::string(name));
        if (it == obj.end()) return;
        const nlohmann::json& j = *it;
        if constexpr (is_hidden_v<V>) {
            (void)j;// internal state — not authorable
        } else if constexpr (std::is_same_v<V, entt::entity>) {
            // Entity reference, authored as the target entity's name. Resolved
            // against the current instantiate() batch — components are applied
            // in a deferred pass after every entity exists, so forward
            // references work regardless of declaration order.
            if (j.is_string()) {
                if (const auto* scope = entityNameScope()) {
                    const auto found = scope->find(j.get<std::string>());
                    if (found != scope->end()) out = found->second;
                    else
                        fmt::print(stderr, "blueprint: entity reference '{}' not found in scene\n",
                                   j.get<std::string>());
                }
            }
        } else if constexpr (std::is_same_v<V, bool>) {
            if (j.is_boolean()) out = j.get<bool>();
        } else if constexpr (std::is_enum_v<V>) {
            if (j.is_number_integer()) out = static_cast<V>(j.get<int64_t>());
        } else if constexpr (std::is_floating_point_v<V>) {
            if (j.is_number()) out = j.get<V>();
        } else if constexpr (std::is_integral_v<V>) {
            if (j.is_number_integer()) out = j.get<V>();
        } else if constexpr (std::is_same_v<V, std::string>) {
            if (j.is_string()) out = j.get<std::string>();
        } else if constexpr (std::is_same_v<V, glm::vec2>) {
            if (j.is_array() && j.size() >= 2) out = { j[0].get<float>(), j[1].get<float>() };
        } else if constexpr (std::is_same_v<V, glm::vec3>) {
            if (j.is_array() && j.size() >= 3) out = { j[0].get<float>(), j[1].get<float>(), j[2].get<float>() };
        } else if constexpr (std::is_same_v<V, glm::vec4>) {
            if (j.is_array() && j.size() >= 4)
                out = { j[0].get<float>(), j[1].get<float>(), j[2].get<float>(), j[3].get<float>() };
        } else if constexpr (std::is_same_v<V, glm::quat>) {
            // [x, y, z, w] — the glTF layout, same as EntityBlueprint rotation.
            if (j.is_array() && j.size() >= 4)
                out = glm::quat(j[3].get<float>(), j[0].get<float>(), j[1].get<float>(), j[2].get<float>());
        } else if constexpr (std::is_same_v<V, glm::mat3> || std::is_same_v<V, glm::mat4>) {
            (void)j;// computed state — not authorable
        } else if constexpr (std::is_aggregate_v<V> && !std::is_array_v<V>) {
            if (j.is_object()) fillFromJson(out, j);// nested aggregate
        }
        // everything else (containers, handles, callbacks): not authorable — skip
    }

    template<typename T> void fillFromJson(T& out, const nlohmann::json& j) {
        constexpr size_t fieldCount = boost::pfr::tuple_size_v<T>;
        [&]<size_t... Is>(std::index_sequence<Is...>) {
            (readField(boost::pfr::get_name<Is, T>(), boost::pfr::get<Is>(out), j), ...);
        }(std::make_index_sequence<fieldCount>{});
    }
#endif
}// namespace detail

class BlueprintComponents {
public:
    using Applier = std::function<void(entt::registry&, entt::entity, const nlohmann::json&)>;

    // Engine-default appliers are registered on first access.
    static BlueprintComponents& instance();

    void registerApplier(const std::string& name, Applier fn) {
        m_appliers[name] = std::move(fn);
    }

    // PFR auto-applier: default-construct T, fill fields by JSON key, emplace.
    // Empty tag types (SunComponent) emplace directly and need no reflection.
    template<typename T> void registerComponent(const std::string& name) {
        registerApplier(name, [](entt::registry& reg, entt::entity e, const nlohmann::json& j) {
            if constexpr (std::is_empty_v<T>) {
                (void)j;
                reg.emplace_or_replace<T>(e);
            } else {
#ifdef VAPOR_HAS_BOOST_PFR
                T component{};
                detail::fillFromJson(component, j);
                reg.emplace_or_replace<T>(e, std::move(component));
#else
                (void)j;
                (void)reg;
                (void)e;
                fmt::print(stderr, "BlueprintComponents: Boost.PFR unavailable; component skipped\n");
#endif
            }
        });
    }

    // True if an applier existed and ran.
    bool apply(const std::string& name, entt::registry& registry, entt::entity e, const nlohmann::json& j) const {
        const auto it = m_appliers.find(name);
        if (it == m_appliers.end()) return false;
        it->second(registry, e, j);
        return true;
    }

private:
    std::unordered_map<std::string, Applier> m_appliers;
};

// Splice `sub` into `dst` under dst entity index `parentIndex` (-1 = top
// level): entities are appended with mesh/light/parent indices rebased, and
// the payload vectors are concatenated. Consumes `sub`.
void appendBlueprint(SceneBlueprint& dst, SceneBlueprint&& sub, int parentIndex);

// Parse scene JSON text into a blueprint. Pure and I/O-free: "source" /
// "prefab" references are recorded on the entities but NOT expanded — that is
// loadSceneBlueprint's job. Nested "children" arrays flatten into the
// parent-indexed layout. Returns ok == false on malformed JSON.
SceneBlueprint parseSceneBlueprint(const std::string& jsonText, const std::string& nameHint = "");

// Load a scene JSON through the FileSystem search paths, parse it, and expand
// every "source" (via AssetManager::loadModel) and "prefab" (recursively)
// reference. Returns ok == false (with a log) if the file is missing or
// malformed; a failed sub-reference logs and leaves that entity empty rather
// than failing the whole scene.
SceneBlueprint loadSceneBlueprint(const std::string& path);

// Decompose an affine transform into TRS (shear is folded into scale lossily —
// fine for DCC-authored content). Shared by the model importers.
void decomposeTransform(const glm::mat4& m, glm::vec3& position, glm::quat& rotation, glm::vec3& scale);

// Turn a blueprint into live entt entities. Creates one root entity (named
// `name`, or the blueprint's name) under `parent`, then one entity per
// EntityBlueprint carrying NameComponent, TransformComponent (local TRS,
// parented) and, where referenced, MeshRendererComponent and the engine light
// components. Every referenced mesh is staged into `scene` exactly once
// (skipped if already staged/registered), so instantiating the same blueprint
// repeatedly shares geometry and draws as GPU instances. Returns the root
// entity (entt::null if the blueprint is not ok); appends every created entity
// (root included) to *outEntities when given.
entt::entity instantiate(
    entt::registry& registry,
    RenderScene& scene,
    const SceneBlueprint& blueprint,
    entt::entity parent = entt::null,
    const std::string& name = "",
    std::vector<entt::entity>* outEntities = nullptr
);

}// namespace Vapor
