// ============================================================================
// Poolrooms — a liminal "pool core" walking demo and the showcase for the RHI
// water stack (FFT spectral surface + planar reflections + refraction +
// projected caustics).
//
// Everything is procedural: the tiled hall (beveled tiles with recessed grout,
// bullnose coping, waterline mosaic band, pillars, skylight wells, a dark
// corridor stub, porthole lamps, a mosaic stair block, bent-tube handrails and
// two glossy tube slides) is generated by poolroom_scene.hpp; the placeholder
// textures by the engine's Vapor::proctex toolkit. Drop real tile photos into
// Res/textures/poolrooms/ (see assets/textures/poolrooms/README.md) and they
// replace the placeholders slot by slot — geometry and UVs are authored so a
// single-tile texture maps one tile per cell.
//
// The player is a Jolt CharacterVirtual (ECS CharacterBodyComponent): walk the
// deck, jump, wade in — below the waterline movement switches to a swim; get
// out via the mosaic stairs or by holding W against a handrail entry.
//
// Two moods: the sunlit pool, and `--flooded` (or the panel checkbox) — the
// whole hall waist-deep in murky warm-green water under a dim ember sun, lamp
// glows smearing across smooth viscous swells.
//
// Controls: WASD move, mouse look (Tab toggles capture), Space jump / swim up,
// LCtrl swim down, LShift sprint, Esc quit. --vulkan / --metal pick the
// backend (water requires the RHI renderer, the default on both).
// ============================================================================

#include "Vapor/asset_manager.hpp"
#include "Vapor/components.hpp"
#include "Vapor/engine_core.hpp"
#include "Vapor/file_system.hpp"
#include "Vapor/graphics_effects.hpp"
#include "Vapor/input_manager.hpp"
#include "Vapor/irenderer.hpp"
#include "Vapor/physics_3d.hpp"
#include "Vapor/render_scene.hpp"
#include "Vapor/systems.hpp"

#include <SDL3/SDL.h>
#include <cstring>
#include <entt/entt.hpp>
#include <fmt/core.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <memory>
#include <string>
#include <vector>

#include "backends/imgui_impl_sdl3.h"
#include "imgui.h"

#include "poolroom_scene.hpp"
#include "Vapor/proctex.hpp"

namespace {

using poolgen::MaterialSlot;

// ── Content conversion ──────────────────────────────────────────────────────

std::shared_ptr<Vapor::Image> toEngineImage(const Vapor::proctex::TextureData& src, const std::string& uri) {
    auto img = std::make_shared<Vapor::Image>();
    img->uri = uri;  // unique key for the renderer's texture cache
    img->width = src.size;
    img->height = src.size;
    img->channelCount = 4;
    img->byteArray = src.pixels;
    return img;
}

// Optional user override: Res/textures/poolrooms/<slot>_<kind>.png replaces
// the procedural placeholder for that slot (albedo/normal/roughness).
std::shared_ptr<Vapor::Image> overrideOr(const char* slotName, const char* kind,
                                         std::shared_ptr<Vapor::Image> fallback) {
    const std::string rel = fmt::format("textures/poolrooms/{}_{}.png", slotName, kind);
    if (FileSystem::instance().resolvePath(rel)) {
        if (auto img = AssetManager::loadImage(rel)) {
            fmt::print("Poolrooms: using user texture '{}'\n", rel);
            return img;
        }
    }
    return fallback;
}

std::shared_ptr<Vapor::Mesh> toEngineMesh(const poolgen::MeshData& src,
                                          std::shared_ptr<Vapor::Material> material) {
    std::vector<Vapor::VertexData> verts(src.positions.size());
    for (size_t i = 0; i < src.positions.size(); ++i) {
        verts[i].position = src.positions[i];
        verts[i].uv = src.uvs[i];
        verts[i].normal = src.normals[i];
        verts[i].tangent = glm::vec4(1, 0, 0, 1);  // MikkTSpace overwrites in initialize()
    }
    auto mesh = std::make_shared<Vapor::Mesh>();
    mesh->hasPosition = true;
    mesh->hasUV0 = true;
    mesh->hasNormal = true;
    mesh->hasTangent = true;
    mesh->primitiveMode = Vapor::PrimitiveMode::TRIANGLES;
    mesh->initialize(verts, src.indices);
    mesh->material = std::move(material);
    return mesh;
}

// Build the per-slot materials: PBR params + procedural (or user) textures.
std::array<std::shared_ptr<Vapor::Material>, size_t(MaterialSlot::Count)> makeMaterials() {
    std::array<std::shared_ptr<Vapor::Material>, size_t(MaterialSlot::Count)> mats;

    auto make = [&](MaterialSlot slot, glm::vec3 base, float rough, float metallic,
                    std::shared_ptr<Vapor::Image> albedo, std::shared_ptr<Vapor::Image> normal,
                    std::shared_ptr<Vapor::Image> roughMap) {
        const char* name = poolgen::materialSlotName(slot);
        auto m = std::make_shared<Vapor::Material>();
        m->name = name;
        m->alphaMode = Vapor::AlphaMode::OPAQUE;
        m->alphaCutoff = 0.5f;
        m->doubleSided = false;
        m->baseColorFactor = glm::vec4(base, 1.0f);
        m->metallicFactor = metallic;
        m->roughnessFactor = rough;
        m->albedoMap = overrideOr(name, "albedo", std::move(albedo));
        m->normalMap = overrideOr(name, "normal", std::move(normal));
        m->roughnessMap = overrideOr(name, "roughness", std::move(roughMap));
        m->useIBL = true;
        mats[size_t(slot)] = m;
    };

    using namespace Vapor::proctex;
    const glm::vec3 white(1.0f);

    // Glazed white ceramic — deck slightly warm, walls cooler, pool tinted.
    make(MaterialSlot::DeckTile, white, 1.0f, 0.0f,
         toEngineImage(tileAlbedo({ 0.78f, 0.76f, 0.73f }, glm::vec3(0.86f), 11u), "pr_deck_a"),
         toEngineImage(tileNormal(0.35f, 0.10f, 12u), "pr_deck_n"),
         toEngineImage(tileRoughness(0.10f, 0.32f, 13u), "pr_deck_r"));
    make(MaterialSlot::WallTile, white, 1.0f, 0.0f,
         toEngineImage(tileAlbedo({ 0.77f, 0.78f, 0.77f }, glm::vec3(0.88f), 21u), "pr_wall_a"),
         toEngineImage(tileNormal(0.30f, 0.08f, 22u), "pr_wall_n"),
         toEngineImage(tileRoughness(0.08f, 0.28f, 23u), "pr_wall_r"));
    make(MaterialSlot::PoolWallTile, white, 1.0f, 0.0f,
         toEngineImage(tileAlbedo({ 0.72f, 0.78f, 0.80f }, glm::vec3(0.85f), 31u), "pr_pwall_a"),
         toEngineImage(tileNormal(0.30f, 0.08f, 32u), "pr_pwall_n"),
         toEngineImage(tileRoughness(0.07f, 0.26f, 33u), "pr_pwall_r"));
    make(MaterialSlot::PoolFloorTile, white, 1.0f, 0.0f,
         toEngineImage(tileAlbedo({ 0.70f, 0.77f, 0.79f }, glm::vec3(0.84f), 41u), "pr_pfloor_a"),
         toEngineImage(tileNormal(0.30f, 0.08f, 42u), "pr_pfloor_n"),
         toEngineImage(tileRoughness(0.07f, 0.26f, 43u), "pr_pfloor_r"));
    // Waterline mosaic: deep pool blue.
    make(MaterialSlot::AccentTile, white, 1.0f, 0.0f,
         toEngineImage(tileAlbedo({ 0.10f, 0.32f, 0.55f }, glm::vec3(0.75f), 51u), "pr_accent_a"),
         toEngineImage(tileNormal(0.40f, 0.10f, 52u), "pr_accent_n"),
         toEngineImage(tileRoughness(0.09f, 0.30f, 53u), "pr_accent_r"));
    // Grout: matte cement in the channels + cove trim.
    make(MaterialSlot::Grout, white, 1.0f, 0.0f,
         toEngineImage(noisyAlbedo({ 0.70f, 0.69f, 0.66f }, 0.10f, 8, 61u), "pr_grout_a"),
         toEngineImage(noisyNormal(0.35f, 12, 62u), "pr_grout_n"),
         toEngineImage(noisyAlbedo(glm::vec3(0.85f), 0.10f, 8, 63u), "pr_grout_r"));
    // Coping: warm cast stone, a touch rougher than the tiles.
    make(MaterialSlot::Coping, white, 1.0f, 0.0f,
         toEngineImage(noisyAlbedo({ 0.80f, 0.77f, 0.72f }, 0.08f, 6, 71u), "pr_coping_a"),
         toEngineImage(noisyNormal(0.5f, 10, 72u), "pr_coping_n"),
         toEngineImage(noisyAlbedo(glm::vec3(0.45f), 0.15f, 6, 73u), "pr_coping_r"));
    // Ceiling plaster.
    make(MaterialSlot::CeilingPlaster, white, 1.0f, 0.0f,
         toEngineImage(noisyAlbedo({ 0.78f, 0.78f, 0.76f }, 0.05f, 5, 81u), "pr_plaster_a"),
         toEngineImage(noisyNormal(0.25f, 8, 82u), "pr_plaster_n"),
         toEngineImage(noisyAlbedo(glm::vec3(0.85f), 0.08f, 5, 83u), "pr_plaster_r"));
    // Corridor: dark, matte, swallow the light.
    make(MaterialSlot::DarkPlaster, white, 1.0f, 0.0f,
         toEngineImage(noisyAlbedo({ 0.09f, 0.10f, 0.10f }, 0.20f, 6, 91u), "pr_dark_a"),
         toEngineImage(noisyNormal(0.3f, 8, 92u), "pr_dark_n"),
         toEngineImage(noisyAlbedo(glm::vec3(0.95f), 0.05f, 6, 93u), "pr_dark_r"));
    // Handrails + lamp rims: brushed stainless.
    make(MaterialSlot::Metal, white, 1.0f, 1.0f,
         toEngineImage(brushedMetalAlbedo({ 0.75f, 0.77f, 0.80f }, 101u), "pr_metal_a"),
         toEngineImage(noisyNormal(0.10f, 24, 102u), "pr_metal_n"),
         toEngineImage(brushedMetalRoughness(0.28f, 103u), "pr_metal_r"));
    // Porthole lamp faces: warm emissive discs. The glow feeds bloom AND the
    // water's planar reflection (the mirror pass shades emissive), which is
    // what smears the lamps across the swells.
    make(MaterialSlot::LampGlow, white, 1.0f, 0.0f,
         toEngineImage(noisyAlbedo({ 0.95f, 0.88f, 0.75f }, 0.03f, 4, 111u), "pr_lamp_a"),
         toEngineImage(noisyNormal(0.05f, 8, 112u), "pr_lamp_n"),
         toEngineImage(noisyAlbedo(glm::vec3(0.6f), 0.05f, 4, 113u), "pr_lamp_r"));
    mats[size_t(MaterialSlot::LampGlow)]->emissiveFactor = glm::vec3(1.0f, 0.82f, 0.55f);
    mats[size_t(MaterialSlot::LampGlow)]->emissiveStrength = 3.5f;
    mats[size_t(MaterialSlot::LampGlow)]->emissiveMap =
        toEngineImage(Vapor::proctex::noisyAlbedo(glm::vec3(1.0f, 0.92f, 0.78f), 0.04f, 4, 114u), "pr_lamp_e");
    // Slide shells: glossy colored plastic (hue from the base color factor;
    // the roughness MAP carries the gloss level, factor stays 1).
    make(MaterialSlot::SlideBlue, glm::vec3(0.16f, 0.38f, 0.88f), 1.0f, 0.0f,
         toEngineImage(noisyAlbedo(glm::vec3(0.92f), 0.03f, 4, 121u), "pr_slide_a"),
         toEngineImage(noisyNormal(0.05f, 8, 122u), "pr_slide_n"),
         toEngineImage(noisyAlbedo(glm::vec3(0.18f), 0.05f, 4, 123u), "pr_slide_r"));
    make(MaterialSlot::SlideViolet, glm::vec3(0.48f, 0.26f, 0.85f), 1.0f, 0.0f,
         toEngineImage(noisyAlbedo(glm::vec3(0.92f), 0.03f, 4, 131u), "pr_slide2_a"),
         toEngineImage(noisyNormal(0.05f, 8, 132u), "pr_slide2_n"),
         toEngineImage(noisyAlbedo(glm::vec3(0.18f), 0.05f, 4, 133u), "pr_slide2_r"));

    return mats;
}

// ── Active water volume ─────────────────────────────────────────────────────
// Which body of water the swim logic answers to. Normal mode: the sunken
// pool. Flooded mode: the whole hall at waist height.
struct WaterVolume {
    glm::vec2 minXZ;
    glm::vec2 maxXZ;
    float level = 0.0f;
};

// ── First-person controller (mouse look + walk/swim/climb intent) ───────────

struct PlayerState {
    entt::entity entity = entt::null;
    float yaw = 0.0f;    // degrees, 0 = looking -Z
    float pitch = 0.0f;  // degrees
    bool mouseCaptured = true;
    bool swimming = false;
    bool climbing = false;
    float eyeHeight = 0.72f;  // above the capsule center (~1.6 m above feet)
};

glm::vec2 mouseDeltaThisFrame;  // accumulated from SDL relative motion events

void updatePlayer(entt::registry& reg, PlayerState& player, const Vapor::InputState& input,
                  const poolgen::PoolroomScene& world, const WaterVolume& water, float deltaTime) {
    (void)deltaTime;  // look/motion are velocity-based; the physics step integrates
    auto* body = reg.try_get<Vapor::CharacterBodyComponent>(player.entity);
    if (!body) return;

    // Mouse look.
    const float lookSpeed = 0.11f;  // degrees per pixel
    player.yaw -= mouseDeltaThisFrame.x * lookSpeed;
    player.pitch -= mouseDeltaThisFrame.y * lookSpeed;
    player.pitch = glm::clamp(player.pitch, -89.0f, 89.0f);

    const float yawRad = glm::radians(player.yaw);
    const glm::vec3 forward(-std::sin(yawRad), 0.0f, -std::cos(yawRad));
    const glm::vec3 right(-forward.z, 0.0f, forward.x);

    glm::vec2 move = input.getVector(Vapor::InputAction::StrafeLeft, Vapor::InputAction::StrafeRight,
                                     Vapor::InputAction::MoveBackward, Vapor::InputAction::MoveForward);
    if (glm::dot(move, move) > 1.0f) move = glm::normalize(move);
    const glm::vec3 moveDir = forward * move.y + right * move.x;

    const glm::vec3 center = body->controller ? body->controller->getPosition()
                                              : reg.get<Vapor::TransformComponent>(player.entity).position;

    // Water state: capsule center below the waterline (with a little slack so
    // wading stays walking).
    player.swimming = center.y < water.level + 0.12f &&
                      center.x > water.minXZ.x && center.x < water.maxXZ.x &&
                      center.z > water.minXZ.y && center.z < water.maxXZ.y;

    // Ladder: inside a climb zone and pushing forward.
    player.climbing = false;
    if (move.y > 0.1f) {
        for (const auto& z : world.ladderZones) {
            if (center.x > z.first.x && center.x < z.second.x &&
                center.y > z.first.y - 0.5f && center.y < z.second.y &&
                center.z > z.first.z && center.z < z.second.z) {
                player.climbing = true;
                break;
            }
        }
    }

    if (!body->controller) {
        body->desiredVelocity = moveDir;
        return;
    }

    if (player.climbing) {
        // Steady rise; jump() detaches from the floor, then the per-frame
        // velocity keeps the climb going (gravity is re-added each fixed step
        // and cancelled here every frame).
        body->desiredVelocity = moveDir * 0.4f;
        if (body->controller->isOnGround()) {
            body->controller->jump(1.8f);
        } else {
            glm::vec3 v = body->controller->getVelocity();
            body->controller->setLinearVelocity(glm::vec3(v.x, 2.0f, v.z));
        }
        body->controller->setMaxSpeed(1.2f);
    } else if (player.swimming) {
        body->controller->setMaxSpeed(1.9f);
        body->desiredVelocity = moveDir;
        float targetVy = -0.18f;  // gentle sink when idle
        if (input.isHeld(Vapor::InputAction::Jump)) targetVy = 1.6f;
        if (input.isHeld(Vapor::InputAction::Crouch)) targetVy = -1.6f;
        // Add a bit of look-directed glide when moving forward.
        targetVy += move.y * -std::sin(glm::radians(player.pitch)) * 1.2f;
        if (body->controller->isOnGround()) {
            if (targetVy > 0.2f) body->controller->jump(glm::min(targetVy, 1.6f));
        } else {
            glm::vec3 v = body->controller->getVelocity();
            body->controller->setLinearVelocity(glm::vec3(v.x, glm::mix(v.y, targetVy, 0.35f), v.z));
        }
    } else {
        const bool sprint = input.isHeld(Vapor::InputAction::Sprint);
        body->controller->setMaxSpeed(sprint ? 5.0f : 3.1f);
        body->desiredVelocity = moveDir;
        if (input.isPressed(Vapor::InputAction::Jump) && body->controller->isOnGround()) {
            body->jumpRequested = true;
        }
    }
}

}  // namespace

auto main(int argc, char* args[]) -> int {
    bool wantVulkan = false, wantMetal = false, startFlooded = false;
    for (int i = 1; i < argc; i++) {
        if (std::strcmp(args[i], "--vulkan") == 0) wantVulkan = true;
        if (std::strcmp(args[i], "--metal") == 0) wantMetal = true;
        if (std::strcmp(args[i], "--flooded") == 0) startFlooded = true;
    }
    (void)wantMetal;

    if (!SDL_Init(SDL_INIT_VIDEO)) {
        fmt::print(stderr, "SDL could not initialize! Error: {}\n", SDL_GetError());
        return 1;
    }

    Uint32 winFlags = SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY;
    GraphicsBackend gfxBackend;
    const char* winTitle;
#if defined(__APPLE__)
    if (wantVulkan) {
        winTitle = "Poolrooms (Vulkan)";
        winFlags |= SDL_WINDOW_VULKAN;
        gfxBackend = GraphicsBackend::Vulkan;
    } else {
        winTitle = "Poolrooms (Metal)";
        winFlags |= SDL_WINDOW_METAL;
        gfxBackend = GraphicsBackend::Metal;
    }
#else
    winTitle = "Poolrooms (Vulkan)";
    winFlags |= SDL_WINDOW_VULKAN;
    gfxBackend = GraphicsBackend::Vulkan;
#endif

    auto window = SDL_CreateWindow(winTitle, 1600, 900, winFlags);
    if (!window) {
        fmt::print(stderr, "Failed to create SDL_Window: {}\n", SDL_GetError());
        return 1;
    }
    int windowWidth, windowHeight;
    SDL_GetWindowSize(window, &windowWidth, &windowHeight);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();

    auto engineCore = std::make_unique<Vapor::EngineCore>();
    engineCore->init();

    auto renderer = createRenderer(gfxBackend, window);
    if (!renderer) {
        fmt::print(stderr, "Failed to create renderer (backend unavailable?)\n");
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    auto physics = std::make_unique<Physics3D>();
    physics->init(engineCore->getTaskScheduler(), renderer->getDebugDraw());
    physics->setDebugEnabled(false);

    auto scene = std::make_shared<RenderScene>("poolrooms");
    entt::registry registry;
    physics->attach(registry);

    // ---- Build the world -----------------------------------------------
    fmt::print("Poolrooms: generating geometry...\n");
    poolgen::PoolroomScene world = poolgen::buildPoolroomScene();
    auto materials = makeMaterials();

    size_t totalTris = 0;
    for (int i = 0; i < int(MaterialSlot::Count); ++i) {
        const poolgen::MeshData& bucket = world.buckets[i];
        if (bucket.empty()) continue;
        totalTris += bucket.triangleCount();
        auto mesh = toEngineMesh(bucket, materials[i]);
        scene->addMesh(mesh);

        auto e = registry.create();
        registry.emplace<Vapor::NameComponent>(e, Vapor::NameComponent{
            fmt::format("poolroom_{}", poolgen::materialSlotName(MaterialSlot(i))) });
        registry.emplace<Vapor::TransformComponent>(e);
        auto& mr = registry.emplace<Vapor::MeshRendererComponent>(e);
        mr.meshes.push_back(mesh);
    }
    fmt::print("Poolrooms: {} triangles across {} material buckets\n",
               totalTris, size_t(MaterialSlot::Count));

    // Upload the geometry pool + register materials/textures, then drop the
    // staging lists so later frames don't re-upload (GLTFViewer pattern).
    renderer->stage(scene);
    scene->stagedMeshes.clear();
    scene->stagedMeshTransforms.clear();

    // Static collision. Jolt's BoxShape carries a convex radius (0.05 by
    // default) and refuses any box whose smallest half-extent is under it, so
    // thin procedural colliders get inflated rather than taking the whole app
    // down with "Failed to create box shape".
    constexpr float kMinHalfExtent = 0.05f;
    for (const poolgen::CollisionBox& box : world.colliders) {
        const glm::vec3 half = glm::max(box.halfExtents, glm::vec3(kMinHalfExtent));
        BodyHandle body = physics->createBoxBody(half, box.center,
                                                 glm::quat(1, 0, 0, 0), BodyMotionType::Static);
        physics->addBody(body, false);
    }

    // ---- Environment ---------------------------------------------------
    entt::entity sunEntity = registry.create();
    entt::entity envEntity = registry.create();
    entt::entity fogEntity = registry.create();
    {
        registry.emplace<Vapor::NameComponent>(sunEntity, Vapor::NameComponent{ "Sun" });
        auto& dl = registry.emplace<Vapor::DirectionalLightComponent>(sunEntity);
        // Steep late-morning sun so the shafts from the skylight wells land
        // on the water and the north deck (retuned per water mode below).
        dl.direction = glm::normalize(glm::vec3(0.28f, -1.0f, 0.22f));
        dl.color = glm::vec3(1.0f, 0.97f, 0.90f);
        dl.intensity = 8.0f;
        registry.emplace<Vapor::SunComponent>(sunEntity);

        registry.emplace<Vapor::NameComponent>(envEntity, Vapor::NameComponent{ "Environment" });
        registry.emplace<Vapor::SkyComponent>(envEntity);

        // Humid haze over the water: a bounded fog bank hugging the hall.
        registry.emplace<Vapor::NameComponent>(fogEntity, Vapor::NameComponent{ "Pool Haze" });
        auto& ft = registry.emplace<Vapor::TransformComponent>(fogEntity);
        ft.position = glm::vec3(0.0f, 1.6f, 0.0f);
        auto& fv = registry.emplace<Vapor::VolumetricFogComponent>(fogEntity);
        fv.bounded = true;
        fv.halfExtent = glm::vec3(12.2f, 3.2f, 5.2f);
        fv.edgeFalloff = 1.5f;
        fv.density = 0.016f;
        fv.albedo = glm::vec3(0.92f, 0.96f, 1.0f);
        fv.anisotropy = 0.62f;
        fv.ambientIntensity = 0.35f;

        // Porthole lamps: a warm point light in front of every glow disc.
        for (const auto& [pos, normal] : world.lamps) {
            auto lampE = registry.create();
            registry.emplace<Vapor::NameComponent>(lampE, Vapor::NameComponent{ "Lamp" });
            auto& lt = registry.emplace<Vapor::TransformComponent>(lampE);
            lt.position = pos + normal * 0.16f;
            auto& pl = registry.emplace<Vapor::PointLightComponent>(lampE);
            pl.color = glm::vec3(1.0f, 0.76f, 0.5f);
            pl.intensity = 2.2f;
            pl.radius = 7.0f;
        }
    }

    // ---- Water (two moods) ----------------------------------------------
    // Normal: the sunlit pool. Flooded: the whole hall knee-deep in murky
    // warm-green water — smooth viscous swells, lamp glows smearing across
    // the surface, dim ember sun. Switchable from the panel (or --flooded).
    WaterVolume waterVol;
    bool floodedMode = startFlooded;
    float sunAzimuthDeg = 52.0f;
    float sunElevationDeg = 66.0f;

    auto applyWaterMode = [&](bool flooded) {
        floodedMode = flooded;
        Vapor::WaterData w{};
        Vapor::WaterSimParams sp{};

        // Shared fields.
        w.normalMapScroll = glm::vec4(1.0f, 0.35f, -0.45f, 1.0f);   // detail-layer scroll
        w.normalMapScrollSpeed = glm::vec2(0.011f, 0.008f);
        w.dampeningFactor = 4.0f;
        w.foamTiling = 2.0f;

        auto& dl = registry.get<Vapor::DirectionalLightComponent>(sunEntity);
        auto& fv = registry.get<Vapor::VolumetricFogComponent>(fogEntity);

        if (!flooded) {
            // Sunlit pool.
            renderer->setWaterGrid(56, 24, 0.25f, 1.0f, 1.0f);
            WaterTransform wt;
            wt.position = glm::vec3(0.0f, world.waterLevel, 0.0f);
            renderer->setWaterTransform(wt);
            waterVol = { world.poolMinXZ, world.poolMaxXZ, world.waterLevel };

            w.surfaceColor = glm::vec4(0.82f, 0.90f, 0.94f, 1.0f);
            w.refractionColor = glm::vec4(0.42f, 0.68f, 0.72f, 1.0f);
            w.refractionDistortionFactor = 0.03f;
            w.refractionHeightFactor = 2.2f;
            w.depthSofteningDistance = 0.30f;
            w.roughness = 0.045f;
            w.reflectance = 0.38f;      // F0 ~ 0.023 — real water
            w.specIntensity = 6.0f;
            w.foamBrightness = 1.1f;
            w.causticsParams = glm::vec4(1.15f, 1.7f, 0.6f, world.waterLevel);
            w.causticsBoundsMin = glm::vec4(world.poolMinXZ.x, world.poolFloorY, world.poolMinXZ.y, 9.0f);
            w.causticsBoundsMax = glm::vec4(world.poolMaxXZ.x, world.waterLevel, world.poolMaxXZ.y, 1.0f);
            w.fftParams = glm::vec4(16.0f, 6.0f, 0.30f, 1.0f);
            w.reflectionParams = glm::vec4(0.85f, 0.05f, 0.5f, 256.0f);

            sp.patchSize = 16.0f;
            sp.windSpeedMps = 1.7f;
            sp.windDirRad = 0.9f;
            // Phillips constant, NOT a wave height — the field variance sums
            // ~65k lattice modes, so RMS height ~= 71 * sqrt(amplitude) here.
            // 1.9e-4 => 1.5 cm RMS, ~4.5 cm crests: an indoor pool's ripple.
            sp.amplitude = 0.00019f;
            sp.choppiness = 1.05f;
            sp.depthMeters = 2.0f;
            sp.smallWaveCutoff = 0.012f;
            sp.directionalSpread = 2.5f;

            sunElevationDeg = 66.0f;
            dl.direction = glm::normalize(glm::vec3(0.28f, -1.0f, 0.22f));
            dl.color = glm::vec3(1.0f, 0.97f, 0.90f);
            dl.intensity = 8.0f;

            fv.density = 0.016f;
            fv.albedo = glm::vec3(0.92f, 0.96f, 1.0f);
            fv.ambientIntensity = 0.35f;
        } else {
            // Flooded hall: waist-deep water everywhere, warm dusk light.
            const float floodLevel = 0.45f;
            renderer->setWaterGrid(96, 40, 0.25f, 1.0f, 1.0f);
            WaterTransform wt;
            wt.position = glm::vec3(0.0f, floodLevel, 0.0f);
            renderer->setWaterTransform(wt);
            waterVol = { glm::vec2(-12.0f, -5.0f), glm::vec2(12.0f, 5.0f), floodLevel };

            // Murky warm green: reflections carry a sepia cast, absorption is
            // fast (dark within a meter), the surface is glassy smooth.
            w.surfaceColor = glm::vec4(0.97f, 0.93f, 0.84f, 1.0f);
            w.refractionColor = glm::vec4(0.11f, 0.16f, 0.12f, 1.0f);
            w.refractionDistortionFactor = 0.045f;
            w.refractionHeightFactor = 0.85f;
            w.depthSofteningDistance = 0.50f;
            w.roughness = 0.02f;
            w.reflectance = 0.42f;
            w.specIntensity = 3.0f;
            w.foamBrightness = 0.85f;
            w.causticsParams = glm::vec4(0.5f, 1.3f, 0.5f, floodLevel);
            w.causticsBoundsMin = glm::vec4(-12.0f, world.poolFloorY, -5.0f, 3.0f);
            w.causticsBoundsMax = glm::vec4(12.0f, floodLevel, 5.0f, 0.8f);
            // Almost no micro detail: the swells read viscous and oily.
            w.fftParams = glm::vec4(16.0f, 6.0f, 0.06f, 1.0f);
            // Strong planar reflection with a heavy wobble — the lamp glows
            // smear into long living streaks.
            w.reflectionParams = glm::vec4(0.94f, 0.085f, 0.35f, 256.0f);

            // Smooth rolling lobes: kill everything shorter than ~22 cm,
            // broad spread, languid clock.
            sp.patchSize = 16.0f;
            sp.windSpeedMps = 2.3f;
            sp.windDirRad = 0.6f;
            // 6.7e-4 => 4.5 cm RMS, ~13 cm crests — a slow flooded swell.
            sp.amplitude = 0.00067f;
            sp.choppiness = 1.3f;
            sp.depthMeters = 1.2f;
            sp.smallWaveCutoff = 0.22f;
            sp.directionalSpread = 1.6f;
            sp.timeScale = 0.75f;

            // Ember dusk through the wells; the lamps carry the room.
            sunElevationDeg = 34.0f;
            const float el = glm::radians(sunElevationDeg), az = glm::radians(sunAzimuthDeg);
            dl.direction = -glm::normalize(glm::vec3(std::cos(el) * std::sin(az), std::sin(el),
                                                     std::cos(el) * std::cos(az)));
            dl.color = glm::vec3(1.0f, 0.68f, 0.42f);
            dl.intensity = 1.1f;

            fv.density = 0.034f;
            fv.albedo = glm::vec3(1.0f, 0.86f, 0.68f);
            fv.ambientIntensity = 0.5f;
        }

        renderer->setWaterSettings(w);
        renderer->setWaterSimParams(sp);
        renderer->setWaterEnabled(true);
        // The sun moved: force the sky/IBL rebake so ambient follows the mood.
        registry.get<Vapor::SkyComponent>(envEntity).dirty = true;
    };
    applyWaterMode(startFlooded);

    // ---- Player --------------------------------------------------------
    PlayerState player;
    {
        auto e = registry.create();
        registry.emplace<Vapor::NameComponent>(e, Vapor::NameComponent{ "Player" });
        auto& t = registry.emplace<Vapor::TransformComponent>(e);
        t.position = world.spawnPosition;
        auto& body = registry.emplace<Vapor::CharacterBodyComponent>(e);
        body.settings.height = 1.75f;
        body.settings.radius = 0.32f;
        body.settings.maxSlopeAngle = 46.0f;

        auto& cam = registry.emplace<Vapor::VirtualCameraComponent>(e);
        cam.isActive = true;
        cam.fov = glm::radians(72.0f);
        cam.aspect = (windowHeight > 0) ? float(windowWidth) / float(windowHeight) : 1.0f;
        cam.near = 0.05f;
        cam.far = 200.0f;

        player.entity = e;
        // Face the pool from the spawn on the north-west deck.
        player.yaw = world.spawnYawDeg;
        player.pitch = -8.0f;
    }
    SDL_SetWindowRelativeMouseMode(window, true);

    // ---- UI -------------------------------------------------------------
    bool pendingFlooded = floodedMode;  // applied at the top of the frame
    renderer->setImGuiCallback([&] {
        ImGui::SetNextWindowPos(ImVec2(12, 12), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowSize(ImVec2(330, 0), ImGuiCond_FirstUseEver);
        ImGui::Begin("Poolrooms");
        ImGui::TextWrapped("WASD move, mouse look (Tab release), Space jump/swim up, "
                           "LCtrl swim down, LShift sprint, Esc quit.");
        ImGui::Checkbox("Flooded hall (liminal dusk)", &pendingFlooded);
        if (auto* body = registry.try_get<Vapor::CharacterBodyComponent>(player.entity);
            body && body->controller) {
            const glm::vec3 p = body->controller->getPosition();
            ImGui::Text("pos (%.1f  %.1f  %.1f)  %s", p.x, p.y, p.z,
                        player.climbing ? "climbing" : (player.swimming ? "swimming" : "walking"));
        }
        ImGui::SeparatorText("Sun");
        bool sunChanged = false;
        sunChanged |= ImGui::SliderFloat("Elevation", &sunElevationDeg, 5.0f, 89.0f, "%.0f deg");
        sunChanged |= ImGui::SliderFloat("Azimuth", &sunAzimuthDeg, -180.0f, 180.0f, "%.0f deg");
        if (sunChanged && sunEntity != entt::null) {
            auto& dl = registry.get<Vapor::DirectionalLightComponent>(sunEntity);
            const float el = glm::radians(sunElevationDeg), az = glm::radians(sunAzimuthDeg);
            dl.direction = -glm::normalize(glm::vec3(std::cos(el) * std::sin(az), std::sin(el),
                                                     std::cos(el) * std::cos(az)));
        }
        ImGui::SeparatorText("Teleport");
        auto teleport = [&](const glm::vec3& pos) {
            if (auto* body = registry.try_get<Vapor::CharacterBodyComponent>(player.entity);
                body && body->controller) {
                body->controller->warp(pos);
            }
        };
        if (ImGui::Button("Deck")) teleport(world.spawnPosition);
        ImGui::SameLine();
        if (ImGui::Button("Pool floor")) teleport(glm::vec3(0.0f, world.poolFloorY + 1.0f, 0.0f));
        ImGui::SameLine();
        if (ImGui::Button("Corridor")) teleport(glm::vec3(-13.6f, 0.9f, 0.0f));
        ImGui::TextDisabled("water tuning: engine panel -> Water Settings");
        ImGui::End();
    });

    fmt::print("Poolrooms loaded. WASD + mouse look, Tab toggles the cursor, Esc quits.\n");

    auto& inputManager = engineCore->getInputManager();
    bool quit = false;
    float time = SDL_GetTicks() / 1000.0f;

    while (!quit) {
        float currTime = SDL_GetTicks() / 1000.0f;
        float deltaTime = glm::min(currTime - time, 0.1f);
        time = currTime;

        inputManager.update(deltaTime);
        mouseDeltaThisFrame = glm::vec2(0.0f);

        SDL_Event e;
        while (SDL_PollEvent(&e) != 0) {
            ImGui_ImplSDL3_ProcessEvent(&e);
            inputManager.processEvent(e);
            switch (e.type) {
                case SDL_EVENT_QUIT:
                    quit = true;
                    break;
                case SDL_EVENT_KEY_DOWN:
                    if (e.key.scancode == SDL_SCANCODE_ESCAPE) quit = true;
                    if (e.key.scancode == SDL_SCANCODE_TAB) {
                        player.mouseCaptured = !player.mouseCaptured;
                        SDL_SetWindowRelativeMouseMode(window, player.mouseCaptured);
                    }
                    break;
                case SDL_EVENT_MOUSE_MOTION:
                    if (player.mouseCaptured) {
                        mouseDeltaThisFrame.x += e.motion.xrel;
                        mouseDeltaThisFrame.y += e.motion.yrel;
                    }
                    break;
                case SDL_EVENT_WINDOW_RESIZED: {
                    windowWidth = e.window.data1;
                    windowHeight = e.window.data2;
                    auto camView = registry.view<Vapor::VirtualCameraComponent>();
                    camView.each([&](auto& cam) {
                        cam.aspect = (windowHeight > 0) ? float(windowWidth) / float(windowHeight) : 1.0f;
                    });
                    break;
                }
                default:
                    break;
            }
        }

        // Apply a panel-requested mode switch before the frame opens (not from
        // inside the ImGui callback, which runs mid-frame).
        if (pendingFlooded != floodedMode) applyWaterMode(pendingFlooded);

        const auto& input = inputManager.getInputState();
        updatePlayer(registry, player, input, world, waterVol, deltaTime);

        engineCore->update(deltaTime);
        physics->process(registry, deltaTime);
        Vapor::TransformSystem::update(registry);
        Vapor::LightGatherSystem::update(registry, scene.get());
        Vapor::SkySystem::update(registry, renderer.get());

        // First-person camera from the interpolated character position.
        auto& cam = registry.get<Vapor::VirtualCameraComponent>(player.entity);
        {
            glm::vec3 center = world.spawnPosition;
            if (auto* body = registry.try_get<Vapor::CharacterBodyComponent>(player.entity);
                body && body->controller) {
                center = body->controller->getInterpolatedPosition(physics->getInterpolationAlpha());
            }
            cam.position = center + glm::vec3(0.0f, player.eyeHeight, 0.0f);
            cam.rotation = glm::quat(glm::vec3(glm::radians(player.pitch), glm::radians(player.yaw), 0.0f));
            glm::mat4 rotation = glm::mat4_cast(cam.rotation);
            glm::mat4 translation = glm::translate(glm::mat4(1.0f), cam.position);
            cam.viewMatrix = glm::inverse(translation * rotation);
            cam.projectionMatrix = glm::perspectiveZO(cam.fov, cam.aspect, cam.near, cam.far);
        }

        Camera tempCamera;
        tempCamera.setEye(cam.position);
        tempCamera.setViewMatrix(cam.viewMatrix);
        tempCamera.setProjectionMatrix(cam.projectionMatrix);

        CameraRenderData camData;
        camData.proj = cam.projectionMatrix;
        camData.view = cam.viewMatrix;
        camData.invProj = glm::inverse(cam.projectionMatrix);
        camData.invView = glm::inverse(cam.viewMatrix);
        camData.nearPlane = cam.near;
        camData.farPlane = cam.far;
        camData.position = cam.position;

        renderer->beginFrame(camData);
        ImGui::NewFrame();
        renderer->invokeImGuiCallback();
        renderer->draw(registry, scene, tempCamera);
        ImGui::Render();
        renderer->endFrame();
    }

    physics->deinit();
    engineCore->shutdown();
    renderer->shutdown();
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
