#pragma once
#include "Vapor/ui_page_system.hpp"
using Vapor::Page;
using Vapor::PageID;
using Vapor::PageSystem;
using Vapor::UIOverlayTag;
using Vapor::UIVisibleTag;
using Vapor::UIDocumentComponent;
using Vapor::UIPageBehaviorComponent;
using Vapor::UINavigatorComponent;
